export const authConstants= {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
    
}

export const studentConstants ={
    GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
    GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
    GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',
    ADD_STUDENTS_REQUEST: 'ADD_STUDENTS_REQUEST',
    ADD_STUDENTS_SUCCESS: 'ADD_STUDENTS_SUCCESS',
    ADD_STUDENTS_FAILURE: 'ADD_STUDENTS_FAILURE',
    UPDATE_STUDENTS_REQUEST: 'UPDATE_STUDENTS_REQUEST',
    UPDATE_STUDENTS_SUCCESS: 'UPDATE_STUDENTS_SUCCESS',
    UPDATE_STUDENTS_FAILURE: 'UPDATE_STUDENTS_FAILURE',
    DELETE_STUDENTS_REQUEST: 'DELETE_STUDENTS_REQUEST',
    DELETE_STUDENTS_SUCCESS: 'DELETE_STUDENTS_SUCCESS',
    DELETE_STUDENTS_FAILURE: 'DELETE_STUDENTS_FAILURE'
}
