# Generated by Django 3.1.4 on 2020-12-30 17:12

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=200)),
                ('period', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='images',
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='studentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=student.models.get_upload_path)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
