# Generated by Django 3.1.4 on 2020-12-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201230_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Semester',
            field=models.IntegerField(default=0),
        ),
    ]
