# Generated by Django 3.1.4 on 2021-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personID',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
