# Generated by Django 3.1.4 on 2021-05-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_personid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Year',
            new_name='Section',
        ),
    ]
