# Generated by Django 3.1.4 on 2021-05-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210511_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='',
        ),
        migrations.AddField(
            model_name='student',
            name='Course_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.course'),
        ),
    ]
